### PR TITLE
Add Documentation url

### PR DESCRIPTION
**Pull request by koutoftimer**
Show documentation URL on pypi

### CODE REVIEW

**Comment by Gallaecio** [comment]
While at it, could you also include Source Code and Issue Tracker links?

**Comment by koutoftimer** [comment]
@Gallaecio like this?

**Review by Gallaecio — APPROVED** [review]

**Comment by Gallaecio** [comment]
Thanks!

**Review by wRAR — APPROVED** [review]

**Comment by wRAR** [comment]
Thanks!

**Pull request merged**
