### PR TITLE
[MRG+1] Add canonicalize_url function #65

### LINKED ISSUE #65: Add canonicalize_url() to w3lib.url
The idea is to move scrapy's `canonicalize_url()` helper to `w3lib.url`
Projects like frontera could be interested: see https://github.com/scrapinghub/frontera/pull/168#issuecomment-234558699

### PR DESCRIPTION
**Pull request by Preetwinder**
This is just a copy of the function and it's tests from scrapy.

Fixes #65

### CODE REVIEW

**Comment by sibiryakov** [comment]
@redapple, what do you think?

**Comment by redapple** [comment]
codecov is complaining about `strict_parsing` test banching. It's true we don't use it.
The related code can be removed (scrapy also has the same dead code)

**Comment by redapple** [comment]
LGTM

**Comment by redapple** [comment]
what do you think @kmike , @dangra , @eliasdorneles ?

**Comment by dangra** [comment]
no pushbacks from me.

**Comment by eliasdorneles** [comment]
Looks good to me too.

**Comment by redapple** [comment]
Thanks @Preetwinder !

**Pull request merged**
