### PR TITLE
[FIX] avoid concating `#` with url if there is no fragment. 

### PR DESCRIPTION
**Pull request by EltonChou**
#72 will always concate `#` with url.
This PR add statement of checking fragment existence.

### CODE REVIEW

**Comment by Gallaecio** [comment]
Closing and reopening to trigger the CI tests again after merging #160.

**Comment by Gallaecio** [comment]
A new day, [a new CI issue](https://github.com/scrapy/w3lib/issues/163) :sweat:

**Comment by joe733** [comment]
Incoming branch is [68 commits behind](https://github.com/EltonChou/w3lib)

**Comment by EltonChou** [comment]
branch is updated. 👍

**Comment by kmike** [comment]
Thanks @EltonChou!

**Comment by kmike** [comment]
flake8 failure should be addressed here: https://github.com/scrapy/w3lib/pull/182

@EltonChou would you mind runing black on your changes, to fix the remaining CI failure?

**Comment by kmike** [comment]
Actually, let me handle the failure. Thanks @EltonChou! Also, thanks @joe733 for the ping :)

**Comment by kmike** [comment]
Merged as #183.

**Pull request closed without merging**
