### PR TITLE
[MRG+1] Added: Removing comments before extracting base URLs. Not a solution to #70, but does help in some cases.

### LINKED ISSUE #70: It's not a good idead to parse HTML text using regular expressions
In [`w3lib.html`](https://github.com/scrapy/w3lib/blob/master/w3lib/html.py) regular expressions are used to parse HTML texts:

``` python
_ent_re = re.compile(r'&((?P<named>[a-z\d]+)|#(?P<dec>\d+)|#x(?P<hex>[a-f\d]+))(?P<semicolon>;?)', re.IGNORECASE)
_tag_re = re.compile(r'<[a-zA-Z\/!].*?>', re.DOTALL)
_baseurl_re = re.compile(six.u(r'<base\s[^>]*href\s*=\s*[\"\']\s*([^\"\'\s]+)\s*[\"\']'), re.I)
_meta_refresh_re = re.compile(six.u(r'<meta\s[^>]*http-equiv[^>]*refresh[^>]*content\s*=\s*(?P<quote>["\'])(?P<int>(\d*\.)?\d+)\s*;\s*url=\s*(?P<url>.*?)(?P=quote)'), re.DOTALL | re.IGNORECASE)
_cdata_re = re.compile(r'((?P<cdata_s><!\[CDATA\[)(?P<cdata_d>.*?)(?P<cdata_e>\]\]>))', re.DOTALL)
```

However this is definitely incorrect when it involves commented contents, e.g.

``` python
>>> from w3lib import html
>>> html.get_base_url("""<!-- <base href="http://example.com/" /> -->""")
'http://example.com/'
```

Introducing "heavier" utilities like `lxml` would solve this issue easily, but that might be an awful idea as `w3lib` aims to be lightweight & fast.  
Or maybe we could implement some quick parser merely for eliminating the commented parts.

Any ideas?

### PR DESCRIPTION
**Pull request by starrify**
Helps resolving the issue in such cases, which does happen in several websites:

``` Python
>>> from w3lib import html
>>> html.get_base_url("""<!-- <base href="http://example.com/" /> -->""")
'http://example.com/'
```

Fixes #70 (since the original #70 report is about this scenario; for other scenarios, we should have separate issues)

### CODE REVIEW

**Comment by redapple** [comment]
Can you add tests for this?
Can you provide example websites showing this issue?

**Comment by starrify** [comment]
Thanks for the notice @redapple . A test has been added.

Here's a sample site which triggers this issue: http://planweb01.rother.gov.uk/OcellaWeb/planningSearch

**Comment by Gallaecio** [comment]
@kmike Could you have a look?

**Comment by Gallaecio** [comment]
This is related to #70

**Comment by joe733** [comment]
Bumping to close outdated PR.

**Review by Gallaecio — APPROVED** [review]

**Review by wRAR — APPROVED** [review]

**Pull request merged**
